import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Button from '@mui/material/Button';
import { Typography } from '@mui/material';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Track My Bill</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Typography variant='h1' fontFamily='Lobster'>
          Welcome to TrackMyBill!
        </Typography>
        <Button variant='outlined' sx={{ mt: 5 }}>
          Track it!
        </Button>
      </main>
    </div>
  );
};

export default Home;
